name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - "28.1"
          - "29.4"
          - "30.2"
    steps:
      - uses: actions/checkout@v4
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      - name: Byte compile
        run: >-
          emacs -Q --batch -L .
          --eval "(setq byte-compile-error-on-warn t)"
          -f batch-byte-compile netbox.el
